### ISSUE TITLE
Dao should offer type-agnostic lookup

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#100]
I've written logic a few times for "if number, lookup by id, else, lookup by name". Seems like we should make that a utility function in the dao anyway

**Comment by AccaliaDeElementia** [comment]
E_AMBIGUITY

topic ids and chat ids can conflict, should this `getGame()` function attempt to retrieve by both topicId and chat ID? should it just retrieve by topicId and then by name?

what is the logic for what field to retrieve by?

**Comment by yamikuronue** [comment]
This was written before the requirement for chats was added; I was just looking for "I will dump whatever parameter you gave me into the dao and get the Game out" functionality. I will accept only looking up topics and names. 

Basically, I only expect chat ID to be an implicit parameter, and I can handle that explicitly in the methods that allow chats to be the source. 

'The more I think about this, the more messy it becomes. Urgh.

**Comment by AccaliaDeElementia** [comment]
okay then.

as described, passing in either topicId or GameName was implemented in 9fd056cc,

the alias update changed behavior slightly in that topicId will match any topicId associated with the game and gameName will match any alias associated with the game.

I'm not sure how to resolve the ambiguity between topic Ids and chat Ids in a clean manner. Internally they're just added as aliases with the prefix `t_` or `c_` as appropriate, but that's an implementation detail and one i'm not sure we want to leak out of the DAO

perhaps if i had been more forward thinking and designed the ids in the provider so that they did not collide and could be used unambiguously interchangeably

**Comment by yamikuronue** [comment]
I think it's honestly fine. The odds of a topic ID and a chat ID being the same in a given game are very slim, and it's very provider-specific.

**Comment by AccaliaDeElementia** [comment]
based on discussions offline and #110 i believe this issue is now :moo: and can be closed.

Is this correct @yamikuronue?

**Comment by yamikuronue** [comment]
uuhh... yes.
