### ISSUE TITLE
Add "group" property to user model

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#79]
Users belong to one or more groups, such as "scum" or "cult". Required support methods:
- Add user to group
- Remove user from group
- Get current action of type by group
- Register action for group (revokes previous action of the same type by any member of the group, but does not revoke actions of that type by non-group members)

**Comment by AccaliaDeElementia** [comment]
adding and removing groups..... that should be able to be handled by the current property mechanisms on users. the group membership is a property of the user, no? so the existing functionality at the DAO level.

as for the group actions, that sounds like a action type of something like 'scum target' that has validation requirements such that one must have the 'scum' property that's enforced in the controller.

unless i'm missing something i don't think there's any DAO work needed to implement this feature.... is there?

**Comment by yamikuronue** [comment]
How do I say, "I don't care who the actor is, give me the latest Scum target action"? Also, currently, revocation of old actions is handled by the data layer, and it keys off the user; I can put it in the controller but now revocation logic is in two places for two use cases

**Comment by AccaliaDeElementia** [comment]
oh, so these actions are not a voted action, they're a last person to act wins? that seems odd for a scum action? i thought there was a need for consensus for the night kill?

**Comment by yamikuronue** [comment]
uuuh... that's a good point? Usually lately either a) the godfather has to submit the action or b) whatever the DM receives last before the time limit they go with. I was implementing B, with A and maybe your C handled in the rules engine update?

**Comment by AccaliaDeElementia** [comment]
A is handleable by only allowing the godfather to submit the action and so is indistingushable from C as far as the DAO is concerned. (the godfather has majority because the godfather is the only person allowed to act)

for B you could handle it by selecting a surrogate user to user for the scum vote and use that user consistently as the voter for the night.... something like, pick the person who has the current vote, or the person voting if there is no current scum action.... it's a bit of a hack, but doable.

as for getting an action of a partucular type without knowing who.... you can use `getActions()` but that does include revoked actions so you'd have to filter those out. `getAction()` requires an actor user....

hmm.........

**Comment by yamikuronue** [comment]
It's a nasty hack, though, and we're trying to implement this functionality as the key piece of this update ;) GetAction has a flag for including or not including revoked actions. Maybe GetActions should do the same? Or split into GetActions and GetAllActions, the way the interface up to the players uses GetPlayers and GetAllPlayers to distinguish between living and all

**Comment by AccaliaDeElementia** [comment]
hmm... okay. Options A and C are handled as is and are indistinguishable as far as the DAO is concerned

option B..... as I see it there's three approaches:
- Allow a specific "Null" actor instance that is unique to each game instance. the Null actor can be used in place of a regular user while still maintaining the "every action must have an actor" rule. this will allow the controller to select the Null actor instead of the voting user for shared group actions. This reducing case B to a special case of C (just like A already is)
- Allow Invisible users to be added to the game to act as surrogates. This acts much like option B but allows the game config to specify custom names for these invisible users. This also allows for other interesting shenanigans such as assigning the second vote of a doublevoter to this invisible user allowing the double voter to conceal their identity if they desire, or even implementing true blind voting if desired.
- Create a second grouped action type that takes a GroupName instead of an actor.

what should we go with here?

**Comment by yamikuronue** [comment]
I don't mind if the person who submitted the action is listed as the actor on the action. In fact, that's probably better for auditing purposes. I just want to be able to query without having to supply an actor. "Give me the most current action of type X, no matter who submitted it" seems like it should be reasonable without resorting to magic strings or invisible actors, right?

**Comment by AccaliaDeElementia** [comment]
hmmm. can do!

**Comment by AccaliaDeElementia** [comment]
Okay as discussed above:
- Add user to group
  - Use of properties on users was determined to be sufficient for this task at the DAO level
- Remove user from group
  - Use of properties on users was determined to be sufficient for this task at the DAO level
- Get current action of type by group
  - New Function on MafiaGame `getActionOfType()` was created to serve this purpose, it retrieves the most recent action of a given type and can be used as such for cases where group actions are not done by consensus.
- Register action for group (revokes previous action of the same type by any member of the group, but does not revoke actions of that type by non-group members)
  - Existing register action function was determined to be sufficient for this purpose at the DAO level, the controller can and should handle an individual MafiaUser's permission to enact an action based on the game rules in play.

I think this clears up everything that was asked of the DAO in this ticket, yes?
