### ISSUE TITLE
New system for unvoting and no-lynch voting

### ISSUE THREAD

**Issue by yamikuronue** [yamikuronue/sockMafia#9]
It needs to 
- Not rely on magic usernames
- Not rely on magic at all if we can help it
- Not add any extra players to the game

**Comment by yamikuronue** [comment]
I think the best solution here is to add a column to the database for retractedInPost.

A retract looks like:
- Get the latest post by the user with a null retractedInPost column
- update the record to have a retractedInPost

A vote looks like:
- Get the latest post by the user with a null retractedInPost column
- If a row exists, update the record to have a retractedInPost
- Record the new vote row

A list would add the isCurrent property to any vote with a null retractedInPost column.

**Comment by dreikin** [comment]
Might have issues with posts close together in time.  There should be a check to make sure the votes are in the right order, so it'd be more like:
A retract looks like:
- Get the latest post by the user with a null retractedInPost column
- If a row exists:
  - If the retraction is newer than the fetched row
    - update the record to have a retractedInPost
  - Otherwise,
    - find where the retraction should go
    - update the surrounding votes' retractedInPost column

A vote looks like:
- Get the latest post by the user with a null retractedInPost column
- If a row exists,
  - If the current vote is newer than the fetched row
    - update the record to have a retractedInPost,
    - Record the new vote row
  - Otherwise,
    - Record the new vote row
    - Find where the vote should go,
    - Update the new row and the surrounding votes' retractedInPost column.
- Else, record the new vote row

A list would add the isCurrent property to any vote with a null retractedInPost column.

**Comment by yamikuronue** [comment]
Surely it's more like:
- Get the latest post by the user with a null retractedInPost column
  - If a row exists,
    - If the current vote is newer than the fetched row
    - update the record to have a retractedInPost,
    - Record the new vote row
  - Otherwise,
    - Record the new vote row with a retractedInPost of the current row's post

**Comment by dreikin** [comment]
If someone decides to rapidly switch votes for whatever reason, there may be more than two disordered votes to sort out, so we can't just assume that the new vote is either the latest or second latest.  Once the reader version (instead of or in addition to the current responsive version) gets going, that may be even more of a problem.

I did forget to make it explicit that the retractedInPost column may need to be checked for post numbers as well, in some cases.  But I haven't had enough tea yet to know if that's more than zero cases.

**Comment by yamikuronue** [comment]
Honestly, that's such an edge case I don't think we should optimize for it.
How often do we think people will do that?

**Comment by RaceProUK** [comment]
I think the chances of a rapid vote switch are low enough the edge case can be ignored, given things like anti-spam measures and other issues that limit posting rates.

**Comment by AccaliaDeElementia** [comment]
rapid voting is bad blay, we should not optimize for bad play strategies.

**Comment by yamikuronue** [comment]
Great, let's get started.
